name: CI pipeline for John the Ripper

on: [push]

env:
  JOHN_VERSION: 1.9.0-jumbo-1

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    container: pipelinecomponents/markdownlint:latest
    steps:
      - uses: actions/checkout@v1
      - name: Run markdown lint
        run: mdl --style all --warnings .
  docker-lint:
    runs-on: ubuntu-latest
    container: pipelinecomponents/hadolint:latest
    steps:
      - uses: actions/checkout@v1
      - name: Run hadolint
        run: hadolint --ignore DL3008 --ignore DL3015 Dockerfile
  build:
    runs-on: ubuntu-latest
    needs: ['docker-lint']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag john-the-ripper:${JOHN_VERSION} --build-arg JOHN_URL=https://www.openwall.com/john/k/john-${JOHN_VERSION}.tar.gz

  release:
    needs: [']
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker push nbaars/john-the-ripper --tag latest