name: CI pipeline for John the Ripper

on: [push]

env:
  JOHN_VERSION: 1.9.0-jumbo-1
  IMAGE_NAME: john-the-ripper:${JOHN_VERSION}

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    container: pipelinecomponents/markdownlint:latest
    steps:
      - uses: actions/checkout@v1
      - name: Run markdown lint
        run: mdl --style all --warnings .

  docker-lint:
    runs-on: ubuntu-latest
    container: pipelinecomponents/hadolint:latest
    steps:
      - uses: actions/checkout@v1
      - name: Run hadolint
        run: hadolint --ignore DL3008 --ignore DL3015 Dockerfile

  build:
    runs-on: ubuntu-latest
    needs: ['docker-lint']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${IMAGE_NAME} --build-arg JOHN_URL=https://www.openwall.com/john/k/john-${JOH_VERSION}.tar.gz
      - name: Save Docker image artifact
        run: docker save -o build.tar ${IMAGE_NAME}
      - name: Upload image artifact
        uses: actions/upload-artifact@master
        with:
          name: docker-image
          path: build.tar

  release:
    needs: ['build']
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Pull Image artifact
        uses: actions/download-artifact@master
        with:
          name: docker-image
      - name: Load image into docker context
        run: docker load -i docker-image/build.tar
      - name: Push the image to Docker Hub
      - run: docker push nbaars/john-the-ripper --tag latest